# Generated by Django 2.0.3 on 2020-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='WardNo',
            field=models.CharField(default=2.3, max_length=20),
            preserve_default=False,
        ),
    ]
