# Generated by Django 2.0.3 on 2020-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('duriation', models.CharField(max_length=120)),
                ('perclass', models.CharField(max_length=120, verbose_name='perclassDuriation')),
                ('is_published', models.BooleanField()),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('startclass', models.CharField(max_length=120)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-list_date',),
            },
        ),
    ]
