# Generated by Django 3.1.3 on 2020-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_workshop_endclasstclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadbudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
