# Generated by Django 3.1.3 on 2020-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_fileadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileadmin',
            old_name='HondingNo',
            new_name='FatherName',
        ),
        migrations.RenameField(
            model_name='fileadmin',
            old_name='wardno',
            new_name='address',
        ),
        migrations.AddField(
            model_name='fileadmin',
            name='type',
            field=models.CharField(default=2.3, max_length=100),
            preserve_default=False,
        ),
    ]
