# Generated by Django 2.0.3 on 2020-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminupload', models.FileField(upload_to='media')),
                ('tittle', models.CharField(max_length=100)),
                ('NIDNumber', models.CharField(max_length=100, unique=True)),
                ('HondingNo', models.CharField(max_length=100)),
                ('wardno', models.CharField(max_length=10)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-list_date',),
            },
        ),
    ]
