# Generated by Django 2.0.3 on 2020-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileadmin',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
