# Generated by Django 3.1.3 on 2020-12-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayor', '0003_officermeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officermeeting',
            name='seminarroom',
        ),
    ]
