# Generated by Django 2.0.3 on 2020-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('marque', models.CharField(max_length=200)),
                ('photo_mayor', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo_ceo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo_slider1', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo_slider2', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('photo_slider3', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-list_date',),
            },
        ),
    ]
