# Generated by Django 2.0.3 on 2020-11-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='tittle',
            new_name='title',
        ),
    ]
