# Generated by Django 2.0.3 on 2020-11-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201122_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
