# Generated by Django 3.1.3 on 2020-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_others_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('list', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('total_student', models.CharField(max_length=250)),
                ('total_teacher', models.CharField(max_length=250)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
