# Generated by Django 3.1.3 on 2020-11-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('placename', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('enviroment', models.CharField(max_length=250)),
                ('closeday', models.CharField(max_length=250)),
            ],
        ),
    ]
