# Generated by Django 3.1.3 on 2020-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_recentlysolveproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlysolveproblem',
            name='photo_main',
            field=models.ImageField(default=2.3, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
