# Generated by Django 3.1.3 on 2020-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recentlysolveproblem_photo_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='councilorinfromation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_main', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wardno', models.CharField(max_length=20)),
                ('phonnumber', models.CharField(max_length=250)),
            ],
        ),
    ]
