# Generated by Django 2.2.10 on 2020-11-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('pyment', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
