# Generated by Django 2.2.10 on 2020-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylicence',
            name='NIDNumber',
            field=models.CharField(default='ovi', max_length=100),
        ),
        migrations.AddField(
            model_name='applylicence',
            name='ward',
            field=models.CharField(default='ovi', max_length=100),
        ),
        migrations.AlterField(
            model_name='applylicence',
            name='pyment',
            field=models.CharField(default='ovi', max_length=100),
        ),
    ]
