# Generated by Django 2.2.10 on 2020-11-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20201117_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylicence',
            name='email',
        ),
    ]
