# Generated by Django 2.0.3 on 2020-11-18 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0003_remove_applylicence_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100)),
                ('wardno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('HondingNo', models.CharField(max_length=100)),
                ('PreviousTax', models.CharField(max_length=100)),
                ('SelectFloor', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='applylicence',
            name='FatherName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
