# Generated by Django 2.0.3 on 2020-11-19 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0006_homeapplication_nidnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardno', models.CharField(max_length=100)),
                ('HoldingNo', models.CharField(max_length=100)),
                ('taxyear', models.CharField(max_length=100)),
                ('TaxType', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('pictureowner', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
