# Generated by Django 2.0.3 on 2020-11-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_hometax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometax',
            old_name='wardno',
            new_name='ward_no',
        ),
    ]
