# Generated by Django 2.0.3 on 2020-11-20 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0008_auto_20201119_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlinebdapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonalNumber', models.CharField(max_length=17, unique=True)),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('BithofDate', models.CharField(max_length=100)),
                ('PresentAddress', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('subdistict', models.CharField(max_length=100)),
                ('oldpic', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
