# Generated by Django 2.0.3 on 2020-11-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0009_onlinebdapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProblemType', models.CharField(max_length=100)),
                ('WardNo', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Breif', models.CharField(max_length=250)),
                ('ProblemPicture', models.ImageField(upload_to='photo')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='hometax',
            name='pictureowner',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='onlinebdapply',
            name='oldpic',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
