# Generated by Django 3.1.3 on 2020-12-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_publicfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicfeedback',
            name='problemtype',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
